export const staticBreeds = {
  Dog: [
    "Affenpinscher",
    "Afghan Hound",
    "Airedale Terrier",
    "Akita",
    "Alaskan Malamute",
    "American Eskimo Dog",
    "American Foxhound",
    "American Pit Bull Terrier",
    "American Staffordshire Terrier",
    "Anatolian Shepherd Dog",
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Australian Terrier",
    "Basenji",
    "Basset Hound",
    "Beagle",
    "Bearded Collie",
    "Bedlington Terrier",
    "Belgian Malinois",
    "Belgian Sheepdog",
    "Belgian Tervuren",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Black and Tan Coonhound",
    "Bloodhound",
    "Border Collie",
    "Border Terrier",
    "Borzoi",
    "Boston Terrier",
    "Bouvier des Flandres",
    "Boxer",
    "Boykin Spaniel",
    "Briard",
    "Brittany",
    "Brussels Griffon",
    "Bull Terrier",
    "Bulldog",
    "Bullmastiff",
    "Cairn Terrier",
    "Canaan Dog",
    "Cane Corso",
    "Cardigan Welsh Corgi",
    "Cavalier King Charles Spaniel",
    "Chesapeake Bay Retriever",
    "Chihuahua",
    "Chinese Crested",
    "Chinese Shar-Pei",
    "Chow Chow",
    "Clumber Spaniel",
    "Cockapoo",
    "Cocker Spaniel",
    "Collie",
    "Coonhound",
    "Corgi",
    "Coton de Tulear",
    "Dachshund",
    "Dalmatian",
    "Doberman Pinscher",
    "Dogue de Bordeaux",
    "Dutch Shepherd",
    "English Bulldog",
    "English Cocker Spaniel",
    "English Foxhound",
    "English Setter",
    "English Springer Spaniel",
    "English Toy Spaniel",
    "Entlebucher Mountain Dog",
    "Eskimo Dog",
    "Field Spaniel",
    "Finnish Lapphund",
    "Finnish Spitz",
    "Flat-Coated Retriever",
    "French Bulldog",
    "German Pinscher",
    "German Shepherd",
    "German Shorthaired Pointer",
    "German Wirehaired Pointer",
    "Giant Schnauzer",
    "Glen of Imaal Terrier",
    "Goldador",
    "Golden Retriever",
    "Goldendoodle",
    "Gordon Setter",
    "Great Dane",
    "Great Pyrenees",
    "Greater Swiss Mountain Dog",
    "Greyhound",
    "Harrier",
    "Havanese",
    "Hovawart",
    "Ibizan Hound",
    "Icelandic Sheepdog",
    "Irish Setter",
    "Irish Terrier",
    "Irish Water Spaniel",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Jack Russell Terrier",
    "Japanese Chin",
    "Japanese Spitz",
    "Japanese Terrier",
    "Kangal Dog",
    "Karelian Bear Dog",
    "Keeshond",
    "Kerry Blue Terrier",
    "King Charles Spaniel",
    "Klee Kai",
    "Komondor",
    "Kuvasz",
    "Labrador Retriever",
    "Lagotto Romagnolo",
    "Lakeland Terrier",
    "Lancashire Heeler",
    "Leonberger",
    "Lhasa Apso",
    "Lowchen",
    "Maltese",
    "Manchester Terrier",
    "Maremma Sheepdog",
    "Mastiff",
    "Mexican Hairless Dog",
    "Miniature Bull Terrier",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Mountain Cur",
    "Mudi",
    "Neapolitan Mastiff",
    "Newfoundland",
    "Norfolk Terrier",
    "Norwegian Buhund",
    "Norwegian Elkhound",
    "Norwegian Lundehund",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling Retriever",
    "Old English Sheepdog",
    "Otterhound",
    "Papillon",
    "Pekingese",
    "Pembroke Welsh Corgi",
    "Petit Basset Griffon Vendeen",
    "Pharaoh Hound",
    "Plott",
    "Pointer",
    "Polish Lowland Sheepdog",
    "Pomeranian",
    "Poodle",
    "Portuguese Water Dog",
    "Preso Canario",
    "Pug",
    "Puggle",
    "Puli",
    "Pumi",
    "Pyrenean Mastiff",
    "Pyrenean Shepherd",
    "Rat Terrier",
    "Redbone Coonhound",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Saint Bernard",
    "Saluki",
    "Samoyed",
    "Schipperke",
    "Scottish Deerhound",
    "Scottish Terrier",
    "Sealyham Terrier",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Shih Tzu",
    "Siberian Husky",
    "Silky Terrier",
    "Skye Terrier",
    "Sloughi",
    "Small Munsterlander Pointer",
    "Soft Coated Wheaten Terrier",
    "Spanish Water Dog",
    "Spinone Italiano",
    "Staffordshire Bull Terrier",
    "Standard Schnauzer",
    "Sussex Spaniel",
    "Swedish Vallhund",
    "Tibetan Mastiff",
    "Tibetan Spaniel",
    "Tibetan Terrier",
    "Toy Fox Terrier",
    "Treeing Walker Coonhound",
    "Vizsla",
    "Weimaraner",
    "Welsh Terrier",
    "West Highland White Terrier",
    "Whippet",
    "Wirehaired Pointing Griffon",
    "Xoloitzcuintli",
    "Yorkshire Terrier",
  ],

  Cat: [
    "Siamese",
    "Persian",
    "Maine Coon",
    "Sphynx",
    "Ragdoll",
    "Bengal",
    "British Shorthair",
    "Abyssinian",
    "Scottish Fold",
    "Norwegian Forest Cat",
    "Himalayan",
    "Russian Blue",
    "Oriental Shorthair",
    "Cornish Rex",
    "Devon Rex",
    "Manx",
    "American Shorthair",
    "Turkish Angora",
    "Birman",
    "Domestic Shorthair",
    "Balinese",
    "Burmese",
    "Chartreux",
    "Cymric",
    "Egyptian Mau",
    "Exotic Shorthair",
    "Havana Brown",
    "Japanese Bobtail",
    "Korat",
    "LaPerm",
    "Nebelung",
    "Pixiebob",
    "Somali",
    "Tonkinese",
    "Toyger",
    "Ukrainian Levkoy",
],

Bird: [
    "Parakeet",
    "Cockatiel",
    "Lovebird",
    "Budgerigar",
    "Canary",
    "African Grey Parrot",
    "Cockatoo",
    "Macaw",
    "Conure",
    "Eclectus Parrot",
    "Quaker Parrot",
    "Pionus Parrot",
    "Senegal Parrot",
    "Finch",
    "Dove",
    "Pigeon",
    "Lorikeet",
    "Poicephalus",
    "Rosella",
    "Kakapo",
    "Sun Conure",
    "Bourke's Parakeet",
    "Blue-and-Gold Macaw",
    "Meyer's Parrot",
    "Black-capped Conure",
    "Hyacinth Macaw",
    "Caique",
    "Alexandrine Parakeet",
    "Rose-ringed Parakeet",
],

Rabbit: [
    "Dutch",
    "Lop",
    "Flemish Giant",
    "Rex",
    "Angora",
    "Holland Lop",
    "Mini Rex",
    "Jersey Wooly",
    "English Angora",
    "Mini Lop",
    "Himalayan Rabbit",
    "Californian Rabbit",
    "Chinchilla Rabbit",
    "Harlequin Rabbit",
    "Netherland Dwarf",
    "Polish Rabbit",
    "Silver Fox Rabbit",
    "Thrianta Rabbit",
    "Velveteen Lop",
    "American Rabbit",
    "Silver Marten Rabbit",
    "Havana Rabbit",
    "Belgian Hare",
    "Blanc de Hotot",
    "Giant Chinchilla Rabbit",
    "English Spot",
    "Tan Rabbit",
    "Mini Satin",
    "American Fuzzy Lop",
],

Hamster: [
    "Syrian",
    "Dwarf Campbell",
    "Dwarf Winter White",
    "Roborovski",
    "Chinese",
    "Teddy Bear",
    "Black Bear",
    "Golden Hamster",
    "Panda Hamster",
    "Satin Hamster",
    "Long-Haired Roborovski",
    "Short-Haired Roborovski",
    "Robo Dwarf Hamster",
    "Golden Dwarf Hamster",
    "Chinese Striped Hamster",
    "Chinese Dwarf Hamster",
    "Greater Long-tailed Hamster",
    "Mongolian Gerbil",
    "Indian Pygmy Jerboa",
    "Campbell's Dwarf Hamster",
],

Fish: [
    "Betta",
    "Guppy",
    "Angelfish",
    "Discus",
    "Goldfish",
    "Tetra",
    "Molly",
    "Platy",
    "Cichlid",
    "Barb",
    "Rasbora",
    "Corydoras",
    "Plecostomus",
    "Swordtail",
    "Killifish",
    "Rainbowfish",
    "Danio",
    "Loach",
    "Catfish",
    "Arowana",
    "Gourami",
    "Parrotfish",
    "Tang",
    "Butterflyfish",
    "Clownfish",
    "Pufferfish",
    "Discus Fish",
    "Angelfish",
    "Bichir",
    "Archerfish",
    "Firemouth Cichlid",
],

Other: [
    "Guinea Pig",
    "Ferret",
    "Chinchilla",
    "Hedgehog",
    "Sugar Glider",
    "Snake",
    "Turtle",
    "Lizard",
    "Frog",
    "Tarantula",
    "Hermit Crab",
    "Axolotl",
    "Beta Fish",
    "Goldfish",
    "Parrotfish",
    "Iguana",
    "Salamander",
    "Axolotl",
    "Snail",
    "African Land Snail",
    "Tortoise",
    "Millipede",
    "Centipede",
    "Bearded Dragon",
    "Gecko",
    "Tegu",
    "Ball Python",
    "Corn Snake",
    "Garter Snake",
    "Boa Constrictor",
    "Monitor Lizard",
    "Chameleon",
],
};

