export const staticBreeds = {
    Dog: [
      "Bulldog",
      "Labrador Retriever",
      "German Shepherd",
      "Golden Retriever",
      "Poodle",
      "Beagle",
      "Rottweiler",
      "Siberian Husky",
      "Boxer",
      "Dachshund",
      "Shih Tzu",
      "Doberman Pinscher",
      "Great Dane",
      "Chihuahua",
      "Cocker Spaniel",
      "Pug",
      "Australian Shepherd",
      "Border Collie",
      "Shetland Sheepdog",
      "Alaskan Malamute",
    ],
    Cat: [
      "Siamese",
      "Persian",
      "Maine Coon",
      "Sphynx",
      "Ragdoll",
      "Bengal",
      "British Shorthair",
      "Abyssinian",
      "Scottish Fold",
      "Norwegian Forest Cat",
      "Himalayan",
      "Russian Blue",
      "Oriental Shorthair",
      "Cornish Rex",
      "Devon Rex",
      "Manx",
      "American Shorthair",
      "Turkish Angora",
      "Birman",
      "Domestic Shorthair",
    ],
    Bird: [
      "Parakeet",
      "Cockatiel",
      "Lovebird",
      "Budgerigar",
      "Canary",
      "African Grey Parrot",
      "Cockatoo",
      "Macaw",
      "Conure",
      "Eclectus Parrot",
      "Quaker Parrot",
      "Pionus Parrot",
      "Senegal Parrot",
      "Finch",
      "Dove",
      "Pigeon",
      "Lorikeet",
      "Poicephalus",
      "Rosella",
      "Kakapo",
    ],
    Rabbit: [
      "Dutch",
      "Lop",
      "Flemish Giant",
      "Rex",
      "Angora",
      "Holland Lop",
      "Mini Rex",
      "Jersey Wooly",
      "English Angora",
      "Mini Lop",
      "Himalayan Rabbit",
      "Californian Rabbit",
      "Chinchilla Rabbit",
      "Harlequin Rabbit",
      "Netherland Dwarf",
      "Polish Rabbit",
      "Silver Fox Rabbit",
      "Thrianta Rabbit",
      "Velveteen Lop",
      "American Rabbit",
    ],
    Hamster: [
      "Syrian",
      "Dwarf Campbell",
      "Dwarf Winter White",
      "Roborovski",
      "Chinese",
      "Teddy Bear",
      "Black Bear",
      "Golden Hamster",
      "Panda Hamster",
      "Satin Hamster",
      "Long-Haired Roborovski",
      "Short-Haired Roborovski",
    ],
    Fish: [
      "Betta",
      "Guppy",
      "Angelfish",
      "Discus",
      "Goldfish",
      "Tetra",
      "Molly",
      "Platy",
      "Cichlid",
      "Barb",
      "Rasbora",
      "Corydoras",
      "Plecostomus",
      "Swordtail",
      "Killifish",
      "Rainbowfish",
      "Danio",
      "Loach",
      "Catfish",
      "Arowana",
    ],
    Other: [
      "Guinea Pig",
      "Ferret",
      "Chinchilla",
      "Hedgehog",
      "Sugar Glider",
      "Snake",
      "Turtle",
      "Lizard",
      "Frog",
      "Tarantula",
      "Hermit Crab",
      "Axolotl",
      "Beta Fish",
      "Goldfish",
      "Parrotfish",
      "Iguana",
      "Salamander",
      "Axolotl",
      "Snail",
      "African Land Snail",
    ],
  };

 export const staticAnimalTypes = [
    // all pet
    { name: "Dog" },
    { name: "Cat" },
    { name: "Bird" },
    { name: "Rabbit" },
    { name: "Hamster" },
    { name: "Fish" },
    { name: "Other" },
  ];
