export const staticBreeds = {
    Dog: [
      "Bulldog",
      "Labrador Retriever",
      "German Shepherd",
      "Golden Retriever",
      "Poodle",
      "Beagle",
      "Rottweiler",
      "Siberian Husky",
      "Boxer",
      "Dachshund",
      "Shih Tzu",
      "Doberman Pinscher",
      "Great Dane",
      "Chihuahua",
      "Cocker Spaniel",
      "Pug",
      "Australian Shepherd",
      "Border Collie",
      "Shetland Sheepdog",
      "Alaskan Malamute",
    ],
    Cat: [
      "Siamese",
      "Persian",
      "Maine Coon",
      "Sphynx",
      "Ragdoll",
      "Bengal",
      "British Shorthair",
      "Abyssinian",
      "Scottish Fold",
      "Norwegian Forest Cat",
      "Himalayan",
      "Russian Blue",
      "Oriental Shorthair",
      "Cornish Rex",
      "Devon Rex",
      "Manx",
      "American Shorthair",
      "Turkish Angora",
      "Birman",
      "Domestic Shorthair",
      "Balinese",
      "Burmese",
      "Chartreux",
      "Cymric",
      "Egyptian Mau",
      "Exotic Shorthair",
      "Havana Brown",
      "Japanese Bobtail",
      "Korat",
      "LaPerm",
      "Nebelung",
      "Pixiebob",
      "Somali",
      "Tonkinese",
      "Toyger",
      "Ukrainian Levkoy",
  ],
  
  Bird: [
      "Parakeet",
      "Cockatiel",
      "Lovebird",
      "Budgerigar",
      "Canary",
      "African Grey Parrot",
      "Cockatoo",
      "Macaw",
      "Conure",
      "Eclectus Parrot",
      "Quaker Parrot",
      "Pionus Parrot",
      "Senegal Parrot",
      "Finch",
      "Dove",
      "Pigeon",
      "Lorikeet",
      "Poicephalus",
      "Rosella",
      "Kakapo",
      "Sun Conure",
      "Bourke's Parakeet",
      "Blue-and-Gold Macaw",
      "Meyer's Parrot",
      "Black-capped Conure",
      "Hyacinth Macaw",
      "Caique",
      "Alexandrine Parakeet",
      "Rose-ringed Parakeet",
  ],
  
  Rabbit: [
      "Dutch",
      "Lop",
      "Flemish Giant",
      "Rex",
      "Angora",
      "Holland Lop",
      "Mini Rex",
      "Jersey Wooly",
      "English Angora",
      "Mini Lop",
      "Himalayan Rabbit",
      "Californian Rabbit",
      "Chinchilla Rabbit",
      "Harlequin Rabbit",
      "Netherland Dwarf",
      "Polish Rabbit",
      "Silver Fox Rabbit",
      "Thrianta Rabbit",
      "Velveteen Lop",
      "American Rabbit",
      "Silver Marten Rabbit",
      "Havana Rabbit",
      "Belgian Hare",
      "Blanc de Hotot",
      "Giant Chinchilla Rabbit",
      "English Spot",
      "Tan Rabbit",
      "Mini Satin",
      "American Fuzzy Lop",
  ],
  
  Hamster: [
      "Syrian",
      "Dwarf Campbell",
      "Dwarf Winter White",
      "Roborovski",
      "Chinese",
      "Teddy Bear",
      "Black Bear",
      "Golden Hamster",
      "Panda Hamster",
      "Satin Hamster",
      "Long-Haired Roborovski",
      "Short-Haired Roborovski",
      "Robo Dwarf Hamster",
      "Golden Dwarf Hamster",
      "Chinese Striped Hamster",
      "Chinese Dwarf Hamster",
      "Greater Long-tailed Hamster",
      "Mongolian Gerbil",
      "Indian Pygmy Jerboa",
      "Campbell's Dwarf Hamster",
  ],
  
  Fish: [
      "Betta",
      "Guppy",
      "Angelfish",
      "Discus",
      "Goldfish",
      "Tetra",
      "Molly",
      "Platy",
      "Cichlid",
      "Barb",
      "Rasbora",
      "Corydoras",
      "Plecostomus",
      "Swordtail",
      "Killifish",
      "Rainbowfish",
      "Danio",
      "Loach",
      "Catfish",
      "Arowana",
      "Gourami",
      "Parrotfish",
      "Tang",
      "Butterflyfish",
      "Clownfish",
      "Pufferfish",
      "Discus Fish",
      "Angelfish",
      "Bichir",
      "Archerfish",
      "Firemouth Cichlid",
  ],
  
  Other: [
      "Guinea Pig",
      "Ferret",
      "Chinchilla",
      "Hedgehog",
      "Sugar Glider",
      "Snake",
      "Turtle",
      "Lizard",
      "Frog",
      "Tarantula",
      "Hermit Crab",
      "Axolotl",
      "Beta Fish",
      "Goldfish",
      "Parrotfish",
      "Iguana",
      "Salamander",
      "Axolotl",
      "Snail",
      "African Land Snail",
      "Tortoise",
      "Millipede",
      "Centipede",
      "Bearded Dragon",
      "Gecko",
      "Tegu",
      "Ball Python",
      "Corn Snake",
      "Garter Snake",
      "Boa Constrictor",
      "Monitor Lizard",
      "Chameleon",
  ],
  };
  
 export const staticAnimalTypes = [
    // all pet
    { name: "Dog" },
    { name: "Cat" },
    { name: "Bird" },
    { name: "Rabbit" },
    { name: "Hamster" },
    { name: "Fish" },
    { name: "Other" },
  ];
