name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm test

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact-name
        path: path/to/artifact

    - name: Node script to open GitHub repo
      run: |
        node -e "
        (async () => {
          await page.goto('https://github.com/agrabio134/react_refresher');
        })();
        "
