name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install

    - name: Run tests
      run: |
        npm test || echo "No tests specified"
      continue-on-error: true  # This allows the workflow to continue even if no tests are defined

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: ./build  # Change this to the actual path of your build or artifacts

    - name: Node script to open GitHub repo
      run: |
        const puppeteer = require('puppeteer');
        (async () => {
          const browser = await puppeteer.launch();
          const page = await browser.newPage();
          await page.goto('https://github.com/agrabio134/react_refresher');
          await browser.close();
        })();
