name: Screenshot and Upload

on: [push]

jobs:
  screenshot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure this matches Puppeteer's requirements

      - name: Install dependencies
        run: |
          npm install

      - name: Run screenshot script
        run: |
          node screenshot.js
        continue-on-error: true  # Allow the script to continue even if it fails for debugging

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-screenshots
          path: screenshots/
          if-no-files-found: warn
          include-hidden-files: false

      - name: List files in screenshots directory
        run: |
          ls -lh screenshots/  # Verify if the screenshot file exists

