name: Screenshot and Upload

on: [push]

jobs:
  screenshot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Puppeteer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxshmfence-dev \
            libgbm-dev \
            libxkbcommon-x11-0 \
            libasound2

      - name: Create screenshots directory
        run: mkdir -p screenshots  # Ensure screenshots directory exists

      - name: Run screenshot script
        run: node screenshot.js
        continue-on-error: true

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-screenshots
          path: screenshots/
          if-no-files-found: warn
