name: Screenshot Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run the screenshot script
    - name: Run screenshot.js
      run: node screenshot.js

    # Optionally, upload artifacts like screenshots
    - name: Upload screenshot artifact
      uses: actions/upload-artifact@v3
      with:
        name: code-screenshots
        path: screenshots/
